version: "3.9"
services:
  ad-insight-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: ad-insight-service
    container_name: ad-insight-service
    ports:
      - "8081:8080"
    depends_on:
      - redis
    env_file:
      - .env.docker
    restart: always
    networks:
      - app-network
  data-process-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: data-process-service
    container_name: data-process-service
    ports:
      - "8082:8080"
    depends_on:
      - redis
    env_file:
      - .env.docker
    restart: always
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
      - app-network

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - app-network
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge
