# reduce frequency for easier testing
global:
 scrape_interval: 15s
 evaluation_interval: 15s  

rule_files:
  - "/etc/prometheus/alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "data-process-service"
    static_configs:
      - targets: 
        - data-process-service:8080
